executing
innerExceptionFor: exception
	^exception exception.